### PR TITLE
chore: run prettier on master

### PR DESCRIPTION
**Pull request by marcusroberts**
Ran npm run format on master

### CODE REVIEW

**Comment by phated** [comment]
Let's prettierignore the changelog because release-please generates in a different format

**Comment by ospencer** [comment]
@marcusroberts Could you add the changelog to the `.prettierignore`?

**Comment by ospencer** [comment]
Jinx!

**Comment by ospencer** [comment]
You'll also need to drop the changes to the changelog, and then this should be good.

**Comment by marcusroberts** [comment]
How does that look?

**Review by ospencer — APPROVED** [review]
:shipit:

**Pull request merged**
